"""
Blocklist generator service for django-waf.

Reads active BlockRules and writes an nginx map/geo configuration file
declaring $waf_block_ip / $waf_block_ua (action=block) and
$waf_throttle_ip / $waf_throttle_ua (action=throttle) variables. This is an
export utility (#31): it generates the variables and, optionally, validates
and reloads nginx. It does not itself enforce anything, the operator wires
the enforcement (403 on block, limit_req on throttle) into their own server
blocks using the reference include shipped under
``django_waf/conf/nginx/`` (see README.md's nginx Integration section).

BlockRule.objects.for_nginx() (models.py) deliberately excludes
action=challenge rules, alongside the existing action=log_only exclusion
(BR-BL-005): nginx cannot serve or verify a JS proof-of-work, only
WafMiddleware can. detect_ua_rotation, detect_subnet_burst, and
detect_cloud_spray (anomaly_detector.py) all create CHALLENGE rules on
first detection rather than BLOCK, deliberately, since their trigger is a
comparatively weak statistical signal; a CHALLENGE rule from one of these
detectors is therefore middleware-only and never reaches this generator's
output until repeated triggering escalates the same IP to a persistent
BLOCK rule (rule_engine._create_escalation_rule). An operator who wires
only the nginx blocklist for enforcement will not see a first-detection
rule at the edge, only an escalated one.

Writes are atomic via a temp-file-then-rename (BR-BL-002).
"""

from __future__ import annotations

import contextlib
import logging
import os
import shutil
import signal
import subprocess
import tempfile
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from django_waf.models import BlockRule

logger = logging.getLogger("django_waf.blocklist_generator")


def generate_nginx_blocklist(output_path: str | None = None) -> int:
    """Generate the nginx blocklist configuration file from active BlockRules.

    Queries BlockRule.objects.for_nginx() (rule_type in ('ip', 'cidr', 'ua')
    with action in ('block', 'throttle'), BR-BL-001, BR-BL-005) then writes:

    - ``map $http_user_agent $waf_block_ua { ... }`` and
      ``map $http_user_agent $waf_throttle_ua { ... }`` for UA rules
    - ``geo $waf_block_ip { ... }`` and ``geo $waf_throttle_ip { ... }`` for
      IP/CIDR rules

    Block and throttle rules are written to distinct variables (#31): a
    throttle rule never appears in $waf_block_ip/$waf_block_ua, and vice
    versa, so an operator can wire throttle to nginx's ``limit_req`` rather
    than an unconditional 403. See the reference snippet under
    ``django_waf/conf/nginx/`` for the wiring.

    The candidate file is written atomically (BR-BL-002) via a temp file
    then rename. When DJANGO_WAF_NGINX_VALIDATE is True (the default), the
    previous file at ``output_path`` is preserved as a ``.last-good`` copy
    before the candidate is activated, ``nginx -t`` (or
    DJANGO_WAF_NGINX_TEST_COMMAND) is run against the live nginx
    configuration once the candidate is in place, and a validation failure
    triggers an immediate restore of the ``.last-good`` copy so a syntactically
    broken candidate never survives on disk as a reload timebomb. When no
    ``.last-good`` copy exists (first-ever run) and validation fails, the
    freshly-written candidate is removed instead, leaving no file rather
    than a broken one. Validation is skipped gracefully (logged, not raised)
    when the configured test command's binary is not on PATH, so
    environments without a local nginx binary are unaffected.

    Args:
        output_path: Override output path. Defaults to DJANGO_WAF_NGINX_BLOCKLIST_PATH.

    Returns:
        Integer count of rules written to the candidate file. This is the
        count of rules in the generated file regardless of whether
        validation subsequently accepted or rolled it back; callers that
        need to know whether the candidate was actually activated should
        inspect the log output (validation failures are logged at error
        level), see the #31 report for why the return type is unchanged
        from before this change (backward compatibility with existing
        callers of this function, e.g. the management command's dry-run
        preview).
    """
    from django_waf import conf
    from django_waf.models import BlockRule

    dest = output_path or conf.DJANGO_WAF_NGINX_BLOCKLIST_PATH

    rules = list(BlockRule.objects.for_nginx())
    rule_count = len(rules)

    ua_block_rules = [r for r in rules if r.rule_type == "ua" and r.action == "block"]
    ua_throttle_rules = [r for r in rules if r.rule_type == "ua" and r.action == "throttle"]
    ip_block_rules = [r for r in rules if r.rule_type in ("ip", "cidr") and r.action == "block"]
    ip_throttle_rules = [r for r in rules if r.rule_type in ("ip", "cidr") and r.action == "throttle"]

    lines: list[str] = [
        "# Generated by django-waf, do not edit manually\n",
        "# This file is regenerated every 5 minutes by the generate_blocklist task.\n",
        "# Declares variables only; see django_waf/conf/nginx/ for the reference\n",
        "# enforcement snippet (block => 403, throttle => limit_req).\n\n",
    ]

    lines.extend(_render_ua_map("$waf_block_ua", ua_block_rules))
    lines.extend(_render_ua_map("$waf_throttle_ua", ua_throttle_rules))
    lines.extend(_render_ip_geo("$waf_block_ip", ip_block_rules))
    lines.extend(_render_ip_geo("$waf_throttle_ip", ip_throttle_rules))

    conf_dir = os.path.dirname(dest)
    if conf_dir:
        os.makedirs(conf_dir, exist_ok=True)

    # Atomic write: temp file in same directory, then rename (BR-BL-002)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=conf_dir or ".", suffix=".conf.tmp")
    try:
        with os.fdopen(tmp_fd, "w") as fh:
            fh.writelines(lines)
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise

    _activate_candidate(tmp_path, dest)

    logger.info("django-waf: wrote %d rules to %s", rule_count, dest)
    return rule_count


def _render_ua_map(variable: str, rules: list[BlockRule]) -> list[str]:
    """Render an nginx ``map $http_user_agent`` block for one action's UA rules.

    Deduplicates on the rendered key rather than the rule row (#153): two
    distinct BlockRule rows whose patterns escape to the same nginx key
    would otherwise emit a duplicate entry, which nginx accepts but reports
    as a warning on every ``nginx -t`` (observed on a consumer box as
    ``nginx: [warn] duplicate network ...``). First occurrence wins, which
    given the incoming ordering (for_nginx() builds on active(), whose
    ``.order_by("priority")`` replaces Meta.ordering) is the lowest
    ``priority`` value, i.e. the most significant rule for the key. Rules
    tied on priority are in unspecified database order, but they render the
    same key, so which one wins does not change the output.
    """
    lines = [f"map $http_user_agent {variable} {{\n", "    default 0;\n"]
    seen: set[str] = set()
    for rule in rules:
        escaped = _nginx_escape_ua(rule.pattern, rule.match_type)
        if escaped and escaped not in seen:
            seen.add(escaped)
            lines.append(f"    {escaped} 1;\n")
    lines.append("}\n\n")
    return lines


def _render_ip_geo(variable: str, rules: list[BlockRule]) -> list[str]:
    """Render an nginx ``geo`` block for one action's IP/CIDR rules.

    Deduplicates on the rendered address rather than the rule row, for the
    same reason as _render_ua_map (#153); a repeated address in a ``geo``
    block is what produced the reported warning. First occurrence wins.

    The ``seen`` set is local to one call, and the caller invokes this once
    per variable with a disjoint rule list, so the block/throttle split
    (BR-BL-001) is untouched: the same IP under both a block and a throttle
    rule still lands in $waf_block_ip and $waf_throttle_ip alike.
    """
    lines = [f"geo {variable} {{\n", "    default 0;\n"]
    seen: set[str] = set()
    for rule in rules:
        # For IP rules the pattern is already a valid IP or CIDR
        safe = rule.pattern.strip()
        if safe and safe not in seen:
            seen.add(safe)
            lines.append(f"    {safe} 1;\n")
    lines.append("}\n\n")
    return lines


def _activate_candidate(tmp_path: str, dest: str) -> None:
    """Activate a written candidate file at ``dest``, with validation and rollback.

    When DJANGO_WAF_NGINX_VALIDATE is False, this is exactly the previous
    unconditional rename (BR-BL-002), no behaviour change for operators who
    have opted out.

    When True (default): the existing ``dest`` (if any) is preserved as
    ``dest + ".last-good"`` before the candidate is renamed into place, then
    the configured test command is run. A validation failure restores the
    ``.last-good`` copy over ``dest`` (or removes the candidate if there was
    no previous file to restore), so a broken candidate never survives on
    disk. A missing test-command binary is treated as "cannot validate
    here" and logged, not as a validation failure, the candidate is
    activated exactly as if validation were disabled.
    """
    from django_waf import conf

    validate = conf.DJANGO_WAF_NGINX_VALIDATE

    if not validate:
        os.rename(tmp_path, dest)
        return

    last_good = dest + ".last-good"
    had_previous = os.path.isfile(dest)
    if had_previous:
        shutil.copy2(dest, last_good)

    os.rename(tmp_path, dest)

    outcome = _validate_nginx_config()
    if outcome is False:
        logger.error(
            "django-waf: nginx -t failed against the candidate blocklist at %s, activation rolled back",
            dest,
        )
        if had_previous:
            os.rename(last_good, dest)
        else:
            with contextlib.suppress(OSError):
                os.unlink(dest)
        return

    # outcome is True (validated) or None (skipped, binary unavailable):
    # the candidate stays active. Drop the rollback copy so it does not
    # accumulate as a stale artefact next to the live file.
    if had_previous:
        with contextlib.suppress(OSError):
            os.unlink(last_good)


def _validate_nginx_config() -> bool | None:
    """Run the configured nginx syntax-test command.

    Returns:
        True if the test command exits 0 (config valid), False if it exits
        non-zero (config invalid), or None if validation could not be
        attempted at all (test command binary not on PATH), callers must
        treat None as "skip", not as a failure.
    """
    from django_waf import conf

    command = conf.DJANGO_WAF_NGINX_TEST_COMMAND

    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=10)
    except FileNotFoundError:
        logger.info(
            "django-waf: nginx test command %r not found, skipping candidate validation",
            command,
        )
        return None
    except subprocess.TimeoutExpired:
        logger.error("django-waf: nginx test command %r timed out after 10s, treating as failure", command)
        return False
    except OSError as exc:
        logger.error("django-waf: nginx test command %r errored: %s, treating as failure", command, exc)
        return False

    if result.returncode == 0:
        return True

    logger.error(
        "django-waf: nginx test command %r exited %d: %s",
        command,
        result.returncode,
        result.stderr.strip(),
    )
    return False


def reload_nginx() -> bool:
    """Signal nginx to reload its configuration.

    Strategy (in order):
    1. **SIGHUP via PID file** (preferred), reads the nginx master PID from
       ``DJANGO_WAF_NGINX_PID_PATH`` and sends SIGHUP directly. No subprocess,
       no sudo, no PATH required. Just needs read access to the PID file.
    2. **Subprocess command** (fallback), runs ``DJANGO_WAF_NGINX_RELOAD_COMMAND``
       if the PID file is unavailable or unreadable.

    Errors are logged but do not raise, a failed reload leaves the previous
    config active (BR-BL-003).

    Returns:
        True if reload succeeded, False otherwise.
    """
    from django_waf import conf

    # Strategy 1: SIGHUP via PID file
    if conf.DJANGO_WAF_NGINX_PID_PATH:
        result = _reload_via_pid(conf.DJANGO_WAF_NGINX_PID_PATH)
        if result is not None:
            return result
        # PID file unreadable, fall through to command

    # Strategy 2: subprocess command
    return _reload_via_command(conf.DJANGO_WAF_NGINX_RELOAD_COMMAND)


def _reload_via_pid(pid_path: str) -> bool | None:
    """Send SIGHUP to the nginx master process via its PID file.

    Returns:
        True if SIGHUP sent successfully, False if the process doesn't exist,
        None if the PID file is unreadable (caller should fall back).
    """
    try:
        with open(pid_path) as fh:
            pid = int(fh.read().strip())
    except (FileNotFoundError, ValueError, OSError):
        logger.debug("django-waf: PID file %s unreadable, falling back to command", pid_path)
        return None

    try:
        os.kill(pid, signal.SIGHUP)
        logger.info("django-waf: sent SIGHUP to nginx master (PID %d)", pid)
        return True
    except ProcessLookupError:
        logger.error("django-waf: nginx PID %d not found, stale PID file?", pid)
        return False
    except PermissionError:
        logger.warning("django-waf: no permission to signal PID %d, falling back to command", pid)
        return None
    except OSError as exc:
        logger.error("django-waf: error sending SIGHUP to PID %d: %s", pid, exc)
        return False


def _reload_via_command(command: list[str]) -> bool:
    """Reload nginx via a subprocess command."""
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("django-waf: nginx reloaded via command")
            return True
        logger.error(
            "django-waf: nginx reload command failed (exit %d): %s",
            result.returncode,
            result.stderr.strip(),
        )
        return False
    except FileNotFoundError:
        logger.error("django-waf: nginx command not found in PATH, reload skipped")
        return False
    except subprocess.TimeoutExpired:
        logger.error("django-waf: nginx reload command timed out after 10s")
        return False
    except OSError as exc:
        logger.error("django-waf: nginx reload command error: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _nginx_escape_ua(pattern: str, match_type: str) -> str:
    """Format a UA pattern for inclusion in an nginx map block.

    Returns the nginx-formatted pattern string, or empty string if the pattern
    cannot be safely expressed.
    """
    pattern = pattern.strip()
    if not pattern:
        return ""

    if match_type == "exact":
        # Exact match, quote the string
        escaped = pattern.replace('"', '\\"')
        return f'"{escaped}"'

    if match_type in ("regex", "contains"):
        # nginx map uses ~* for case-insensitive regex prefix
        if match_type == "contains":
            # Wrap as a case-insensitive regex
            import re

            escaped = re.escape(pattern)
            return f'"~*{escaped}"'
        # regex, use as-is with ~* prefix
        return f'"~*{pattern}"'

    return ""
